CREATE TABLE sales_partitioned (
  sales_id    INTEGER NOT NULL,
  customer_id INTEGER NOT NULL,
  product_id  INTEGER NOT NULL,
  sale_date   DATE NOT NULL,
  quantity     INTEGER NOT NULL,
  sale_value   DECIMAL (8,0) NOT NULL
)  ENGINE=InnoDB
PARTITION BY RANGE (YEAR(sale_date)) (
  PARTITION p_sales_pre2000 VALUES LESS THAN (2000),
  PARTITION p_sales_2000 VALUES LESS THAN (2001),
  PARTITION p_sales_2001 VALUES LESS THAN (2002),
  PARTITION p_sales_2002 VALUES LESS THAN (2003),
  PARTITION p_sales_2003 VALUES LESS THAN (2004),
  PARTITION p_sales_2004 VALUES LESS THAN (2005),
  PARTITION p_sales_2005 VALUES LESS THAN (2006),
  PARTITION p_sales_2006 VALUES LESS THAN (2007)
) ;
